//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotnetConf2019BCN.Mobile.Features.Localization {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotnetConf2019BCN.Mobile.Features.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Added to cart.
        /// </summary>
        internal static string Alert_Added_To_Cart {
            get {
                return ResourceManager.GetString("Alert_Added_To_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You reached one of the ends for this demo app..
        /// </summary>
        internal static string Alert_Message_DemoApp {
            get {
                return ResourceManager.GetString("Alert_Message_DemoApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, there was an error requesting data over Internet..
        /// </summary>
        internal static string Alert_Message_InternetError {
            get {
                return ResourceManager.GetString("Alert_Message_InternetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, we couldn&apos;t find a camera on this device. Thanks in advance..
        /// </summary>
        internal static string Alert_Message_NoCameraSupport {
            get {
                return ResourceManager.GetString("Alert_Message_NoCameraSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to enter this page without permissions granted..
        /// </summary>
        internal static string Alert_Message_PermissionsNotGranted {
            get {
                return ResourceManager.GetString("Alert_Message_PermissionsNotGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        internal static string Alert_OK {
            get {
                return ResourceManager.GetString("Alert_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK....
        /// </summary>
        internal static string Alert_OK_OKEllipsis {
            get {
                return ResourceManager.GetString("Alert_OK_OKEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Feature not available.
        /// </summary>
        internal static string Alert_Title_FeatureNotAvailable {
            get {
                return ResourceManager.GetString("Alert_Title_FeatureNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to find a camera.
        /// </summary>
        internal static string Alert_Title_NoCameraSupport {
            get {
                return ResourceManager.GetString("Alert_Title_NoCameraSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permissions not granted.
        /// </summary>
        internal static string Alert_Title_PermissionsNotGranted {
            get {
                return ResourceManager.GetString("Alert_Title_PermissionsNotGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unexpected error.
        /// </summary>
        internal static string Alert_Title_UnexpectedError {
            get {
                return ResourceManager.GetString("Alert_Title_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error adding to the cart.
        /// </summary>
        internal static string Snack_Message_AddedToCart_Error {
            get {
                return ResourceManager.GetString("Snack_Message_AddedToCart_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product added to cart.
        /// </summary>
        internal static string Snack_Message_AddedToCart_OK {
            get {
                return ResourceManager.GetString("Snack_Message_AddedToCart_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, type a well-formed absolute URL..
        /// </summary>
        internal static string Snack_Message_InvalidAbsoluteURL {
            get {
                return ResourceManager.GetString("Snack_Message_InvalidAbsoluteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, type non-empty email and password..
        /// </summary>
        internal static string Snack_Message_InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("Snack_Message_InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings saved!.
        /// </summary>
        internal static string Snack_Message_SettingsSaved {
            get {
                return ResourceManager.GetString("Snack_Message_SettingsSaved", resourceCulture);
            }
        }
    }
}
